### ISSUE TITLE
Use a copyright escape code for clarity and maintainability

### ISSUE THREAD

**Issue by eatpro** [Jahmad730/ColmarAcademy#1]
https://github.com/Jahmad730/ColmarAcademy/blob/86d89376cf25fae19e513e683fa9947d993b0073/index.html#L352

A hardcoded copyright symbol like above is not wrong but does not agree with best practices. It is best to use an escape code (like below) so that it will display properly regardless of the machine the code is on and so that it is easier to find for other developers

```&copy;```

**Comment by Jahmad730** [comment]
fixed and pushed, thanks
